### PR TITLE
Fix #9, Unit test for SAMPLE lib

### LINKED ISSUE #9: Add unit test example for sample_lib
**Is your feature request related to a problem? Please describe.**
The SAMPLE library does not implement any unit test.  Actual CFE libraries would typically need to do this. 

**Describe the solution you'd like**
A unit test should be implemented to provide a template for implementing a library unit test (code coverage) using the current framework.

**Additional context**
The unit test for an application (e.g. in sample_app, as in nasa/sample_app#21) is slightly different, as the application typically would not need to expose stubs but a library would.  Therefore both sample_app and sample_lib should implement unit tests.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
Fixes #9

Implements a coverage test for sample_lib code as well as a stub library to facilitate unit test of external code that calls functions within sample_lib.

**Testing performed**
Build with SIMULATION=native ENABLE_UNIT_TESTS=TRUE
Confirm normal CFE operation is unaffected
Confirm unit tests all pass, including new test of "sample_lib"
Confirm "lcov" report now includes sample_lib, and coverage is 100%

**Expected behavior changes**
This adds a new test for "sample_lib" which is part of the make test target, and the line coverage reports now include sample_lib.

**System(s) tested on:**
Ubuntu 18.04 LTS 64-bit

**Additional context**
The coverage test cases are written assuming that previous pull request #10 is already merged.  That is, they exercise/test the logic that was added in this.  Therefore this commit is a child of the commit for the previous pull request.

**Contributor Info**
Joseph Hickey, Vantage Systems, Inc.

**Community contributors**
You must attach a signed CLA (required for acceptance) or reference one already submitted

### CODE REVIEW

**Comment by jphickey** [comment]
NOTE: force-pushed to fix a comment.  No substantive change.

**Comment by skliper** [comment]
CCB 20200122 - Discussed, scoping is lower priority than standard compliance, but preference is to test via available mechanisms (not accessing internals).

**Comment by jphickey** [comment]
Latest push rebases to "master" and removes wrappers used to access the static fields.

**Comment by astrogeco** [comment]
CCB 20200318 - Check if there's any 6.6->6.7 changes. Otherwise Approved.

**Pull request merged**
